### ISSUE TITLE
Create indicator tables

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/obtn#3]
These are tables by indicator, showing comparisons across counties. See [latest report](https://www.tfff.org/sites/default/files/OregonByTheNumbers2020_23Nov.pdf) starting on page 95.

![image](https://user-images.githubusercontent.com/13971585/115414758-2bb9ab80-a1ab-11eb-9073-ce40d23d7368.png)

[I recorded a video to show you how to get started](https://share.getcloudapp.com/eDujg1g0). As I mention in the video, this package has no documentation but what I'm asking you to do is really simple so no need for it at this point, I think. 

I've created a new file for you to work on this in https://github.com/rfortherestofus/obtn/commit/7cbdb3a9cb213c020a3f835cbe54281869622d53.

Let me know if you have any questions!

**Comment by MaiaPelletier** [comment]
Looks great! I'll be starting on this this weekend, and I'll keep you updated in the issues 🙂

**Comment by MaiaPelletier** [comment]
I started on this in https://github.com/rfortherestofus/obtn/commit/cf43561aad44d2236be76ec9edf55af95b8b1855! You can see what the table looks like [here](https://github.com/rfortherestofus/obtn/blob/cf43561aad44d2236be76ec9edf55af95b8b1855/inst/plots/tests/indicator_table.pdf). It needs some tweaks, which I'll make a bit later, but I think it looks pretty good (i.e. incredibly close to the original!) 🙂

**Comment by dgkeyes** [comment]
Thanks, this looks like a great start! Very close to the original!

I just realized that I completely forgot to upload the specs for the table, which would be helpful!

[OBTN_2021_TableSpecs.pdf](https://github.com/rfortherestofus/obtn/files/6379012/OBTN_2021_TableSpecs.pdf)

When you make the tweaks, will you use this as a reference? If you have any questions, please let me know. Thanks!

**Comment by dgkeyes** [comment]
Hey @MaiaPelletier just wanted to see if you have any updates on this. I have a call with the client on Thursday and I'd love to share something with them if possible. Thanks!

**Comment by MaiaPelletier** [comment]
Hey David! Yes, I implemented the style guide that you provided in https://github.com/rfortherestofus/obtn/commit/9924f2723eeb44fadfb20c2922ce0b182a2c4f4e. The one thing that is outstanding is contraining the proportions of the table to fit the ones in the style guide exactly, still need to figure that one out. I actually planned to work on this tonight and tomorrow (since I wasn't able to this past weekend) so hopefully I will be able to actually close this before your call on Thursday!

**Comment by MaiaPelletier** [comment]
No worries and no need to apologize! I totally forgot to update you on that when I did it

**Comment by MaiaPelletier** [comment]
Hey David, I'm pretty much done! Just putting some final touches on it. One quick q: Is the footnote of the table part of the table design or is it added in after?

**Comment by dgkeyes** [comment]
It's part of the table

**Comment by MaiaPelletier** [comment]
Cool! I orginally had it like that but it wasn't in the style guide so I second guessed it. Anyway, its there and also I added the table width constraints in https://github.com/rfortherestofus/obtn/commit/441b8ecbf63e6e6cab1be3303967449c729d9ffe. You can see the example using the Food Insecurity measure [here](https://github.com/rfortherestofus/obtn/blob/441b8ecbf63e6e6cab1be3303967449c729d9ffe/inst/plots/tests/indicator_table_Food_Insecurity_2020.pdf) . The one thing I have left to do tonight is just add an `if` statement in the function that creates the table for measures that don't need percent formatting. I just wanted to get you the finished example file 🙂

**Comment by dgkeyes** [comment]
Thanks! I took a quick look at the PDF and it still looks small and not cropped to the size of the table. Am I missing something? It looks great other than that!

**Comment by MaiaPelletier** [comment]
I used the exact size in inches/pixels from the style guide and so I figured that maybe the tables got resized when they are added to the report (I also noticed the smallness)! If it needs to actually fill the whole page of the, I can try to resize it and keep the proportions so that it fills the page but also keeps the same size constraints :)

**Comment by dgkeyes** [comment]
Yes, sorry, I should have clarified. I do need the PDF output to be the exact size that it is on the reference doc. I want to give it to the designer so she can plop it directly into InDesign. Thanks!

**Comment by MaiaPelletier** [comment]
Hey David, so I (finally) figured out how to [resize these tables](https://github.com/rfortherestofus/obtn/blob/master/inst/plots/tests/indicator_table_Food_Insecurity_2020.pdf) (see in https://github.com/rfortherestofus/obtn/commit/7042a34425481b2439dbd53414faf89617b692f8), however the sizing may be slightly unexact to the exact size of the tables in the report, since the function of resizing the PDFs in `gt` (and also `flextable` and `kableExtra`, since I tried those as well) doesn't allow for sizing in specific aspect ratios/pixels, instead it essentially just "zooms" in on the table to fill the page. I also saved an example to [PNG ](https://github.com/rfortherestofus/obtn/blob/master/inst/plots/tests/indicator_table_Food_Insecurity_2020.png) rather than PDF, since the sizing might be more exact with PNG. When you have the time, take a look at the two and let me know what you think! If you prefer PNG over PDF, I can update my code to export to PNG rather than PDF instead 🙂

**Comment by dgkeyes** [comment]
Thanks for the update! This is trickier than I expected! On these two options, here's what I see:

1. The PNG looks really small. Maybe I'm missing something? PNG can work, but we need it to be both the right size and high resolution. Can we do this? 
1. The PDF seems to go across multiple pages, which won't work unfortunately. 

Please let me know what you think. If it turns out this simple isn't possible, that's totally fine. Just let me know. Thanks!

**Comment by MaiaPelletier** [comment]
I'm going to look into other possibilities today to see if there's anything I'm missing but based on what you're seeing with the options I uploaded, I'm thinking this may not be possible to constrain the sizes in a reproducible way. The PDF I uploaded only spanned 1 page on my device and I'm not sure about increasing the resolution of the PNG either (another thing I'll double check today). I'm starting to think that the details of the export depends on the resolution of the machine being worked on. Anyway, I will get back to you today with an answer on if I think this is doable or not!

**Comment by MaiaPelletier** [comment]
Ok! So here is where I am at as of now, assuming I am understanding everything that I'm learning properly: I don't think this is going to be possible to do in a reproducible manner in PDF. However, I think this may be possible with PNG with two considerations to your points about resolution and size:

- When exporting to PNG (or PDF), `gt` uses the package `webshot` in the background which essentially takes "screenshots" of the HTML produced by `gt` to render the tables. You can produce higher quality PNGs by "zooming" on these screenshots, but I **can't control the **_exact_** resolution upon exporting. I can just ensure that the quality is "high".** In https://github.com/rfortherestofus/obtn/commit/8e659410a8dd28da3c00d100ed3cc3b10319e233 I uploaded [a much higher resolution image](https://github.com/rfortherestofus/obtn/blob/master/inst/plots/tests/indicator_table_Food_Insecurity_2020.png) than the first one, so you can see what I mean by that.
- I am still **unsure about the how exact the sizing is when exporting** with `webshot`. I've asked this question on a couple forums ( you might see it on twitter 😅 ) because I'm struggling finding the answer to this myself. I'm planning on returning to this issue **tomorrow** afternoon to get you a 100% sure answer on this.

**Comment by dgkeyes** [comment]
Thanks, Maia. Just FYI, I'm moving super slow because we're moving tomorrow. 

I appreciate the detailed updates. Please let me know what else, if anything, you figure out. To be honest, I'm thinking it's probably best to just scrap this, but if you find a good solution, let me know!

**Comment by MaiaPelletier** [comment]
No worries, I figured that was happening! Hope the move went well! 

I definitely didn't get any decent responses. I waited a while to update on this to see if I would get more responses but I didn't hear anything over the week, so I'm thinking there isn't a perfect solution right now. Should I hold off on working more on this then?

**Comment by dgkeyes** [comment]
Yeah, let's hold off on this. It just doesn't seem worth it. It's annoying to do by hand but not **that** annoying. Thanks for trying!
